# Generated by Django 3.0.7 on 2021-01-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectuser', models.CharField(choices=[('1', 'bhuvana'), ('2', 'teja'), ('3', 'siva'), ('4', 'kalyani'), ('5', 'pooji'), ('6', 'prani'), ('7', 'vyshu'), ('8', 'nandu'), ('9', 'mouni'), ('10', 'nikki')], default='1', max_length=20)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
